### ISSUE TITLE
Plotting not working for some figures

### ISSUE THREAD

**Issue by trichter** [trichter/qopen#1]
When running

```
qopen --tutorial
qopen
```

I get errors on the command line

```
QPixmap: It is not safe to use pixmaps outside the GUI thread
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed. 
```

and/or in example.log.

```
Traceback (most recent call last):
  File ".../anaconda/lib/python2.7/site-packages/qopen/core.py", line 1654, in invert
    plot_eventsites_options=plot_eventsites_options)
  File ".../anaconda/lib/python2.7/site-packages/qopen/core.py", line 1783, in plot_
    plot_eventresult(result, title=title, fname=fname, **pkwargs)
  File ".../anaconda/lib/python2.7/site-packages/qopen/imaging.py", line 420, in plot_eventresult
    _savefig(fig, fname=fname, title=title)
  File ".../anaconda/lib/python2.7/site-packages/qopen/imaging.py", line 79, in _savefig
    dpi=dpi)
  File ".../anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 688, in savefig
    res = fig.savefig(*args, **kwargs)
...
  File ".../anaconda/lib/python2.7/site-packages/matplotlib/mathtext.py", line 2809, in subsuper
    last_char.width = last_char._metrics.advance
AttributeError: 'Hlist' object has no attribute '_metrics' 
```

What is the problem?

**Comment by trichter** [comment]
Please update your `matplotlib` installation. The problem should be solved.
